export const TEXTS = {
	polish: {
		brandName: "RED-ANTENNA",
		homeBtnP: "High Performance Antenna System",
		pl: "Polski",
		en: "Angielski",
		navBtnProducts: "PRODUKTY",
		navBtnAbout: "O NAS",
		navBtnContact: "KONTAKT",
		header: "ANTENY WYSOKIEJ KLASY",
		headerP: "GDY LICZY SIĘ WYDAJNOŚĆ I JAKOŚĆ",
		articleTitle1: "RĘCZNIE ROBIONE W POLSCE",
		article1:
			"Używamy wyłącznie najlepszych dostępnych komponentów, dbamy o najwyższą jakość wykonania.",
		articleTitle2: "BEZKOMPROMISOWO ZAPROJEKTOWANE",
		article2:
			"Bezkompromisowe założenia projektowe – optymalnie zaprojektowane anteny.",
		articleTitle3: "POTWIERDZONA EFEKTYWNOŚĆ",
		article3:
			"Nasze anteny testowane są pod kątem faktycznej efektywności wykorzystując raporty WSPR. ",
		aboutTitle: "NASZA MISJA",
		aboutText:
			"Antena jest bez wątpienia najważniejszym z elementów mających skuteczny wpływ na zasięg każdego systemu nadawczo-odbiorczego. Naszym celem jest tworzenie bezkompromisowych anten, optymalnie zaprojektowanych, cechujących się najlepszymi parametrami i najwyższą jakością wykonania. Osiągnęliśmy go poprzez odpowiedni dobór elementów składowych, szereg testów praktycznych i wytrzymałościowych oraz pomiarów. Bazujemy na rzetelnych opracowaniach naukowych, eksperymentach wielu radioamatorów oraz przede wszystkim własnych wieloletnich doświadczeniach w budowie systemów antenowych i pracy na pasmach krótkofalowych. Dlatego też nasze anteny wyprzedzają pod wieloma względami konkurencyjne produkty dostępne na rynku i tworzą ekskluzywną linię anten wysokiej klasy (tzw. High End)",
		footer: {
			titleStore: "Sklep Firmowy",
			titleContact: "Kontakt",
			titleAbout: "O Nas",
			ourStore: "Zapraszamy do naszego sklepu stacjonarnego",
			open: "Pon-Pt",
			hours: "9:00 - 18:00",
			street: "ul. Bieżuńska 1 lok 51",
			postCode: "03-578",
			city: "Warszawa",
			country: "Polska",
			onlineStore: "Sklep online",
			onlineStoreLink: "https://www.ercomer.pl/",
			phoneMain: "(+48) 22 270 12 15",
			phoneSec: "(+48) 798 792 927",
			email: "info@ercomer.com",
			about: "RED-ANTENNA jest marką handlową firmy ERcomER. Powstała w oparciu o wieloletnie doświadczenie, pasję i chęć tworzenia najlepszych produktów w zakresie osprzętu radiokomunikacyjnego.",
		},
	},
	english: {
		brandName: "RED-ANTENNA",
		homeBtnP: "High Performance Antenna System",
		pl: "Polish",
		en: "english",
		navBtnProducts: "PRODUCTS",
		navBtnAbout: "ABOUT",
		navBtnContact: "CONTACT",
		header: "HIGH-END ANTENNAS",
		headerP: "WHEN PERFORMANCE AND QUALITY MATTERS",
		articleTitle1: "HANDCRAFTED IN POLAND",
		article1:
			"We use only the best components available, and take care of the highest quality workmanship.",
		articleTitle2: "UNCOMPROMISED DESIGN",
		article2: "Made without cutting corners",
		articleTitle3: "PROVEN EFFECTIVENESS",
		article3:
			"Our antennas are tested for actual effectiveness using WSPR reports. ",
		aboutTitle: "OUR MISSION",
		aboutText:
			"The antenna is undoubtedly the most important of the elements that effectively influence the range of any transceiver system. Our goal is to create uncompromising antennas, optimally designed, featuring the best parameters and highest quality workmanship. We have achieved it through appropriate selection of components, a series of practical and endurance tests and measurements. We rely on reliable scientific studies, the experiments of many radio amateurs and, above all, our own many years of experience in building antenna systems and working on the shortwave bands. Therefore, our antennas are ahead of competitive products on the market in many respects and form an exclusive line of high-end (so-called High End) antennas.",
		footer: {
			titleStore: "Store",
			titleContact: "Contact",
			titleAbout: "About Us",
			ourStore: "We invite you to visit our stationary store",
			open: "Mon-Fri",
			hours: "9:00 - 18:00",
			street: "ul. Bieżuńska 1 lok 51",
			postCode: "03-578",
			city: "Warszawa",
			country: "Poland",
			onlineStore: "Online Store",
			onlineStoreLink: "https://www.ercomer.pl/",
			phoneMain: "(+48) 22 270 12 15",
			phoneSec: "(+48) 798 792 927",
			email: "info@ercomer.com",
			about: "RED-ANTENNA is a trademark of ERcomER. It was established based on years of experience, passion and desire to create the best products in the field of radio communication equipment.",
		},
	},
};
