/*Web Design & Development by: Jakub "Jacek" Bedynek | kuba.xray@gmail.com*/

export const TEXTS = {
	polish: {
		common: {
			pl: true,
			storeLocation: "ul. Bieżuńska 1 lok. 51 03-578 Warszawa",
			open: "Pon-Pt 10:00 - 18:00",
			country: "Polska",
			location: "https://maps.app.goo.gl/s7hr6nTTHfrLKx3w6",
			onlineStoreLink: "https://www.ercomer.pl/",
			phoneMain: "(+48) 22 270 12 15",
			phoneSec: "(+48) 798 792 927",
			phoneService: "(+48) 22 270 12 07",
			email: "info@ercomer.com",
			phoneMainTitle: "Telefon główny",
			phoneSecTitle: "Telefon komórkowy",
			phoneServiceTitle: "Dział produkcji i serwisu",
			emailTitle: "Adres mailowy",
			storeTitle: "Sklep stacjonarny",
			onlineStore: "Sklep online",
			hoursTitle: "Godziny otwarcia",
		},

		nav: {
			brandName: "RED-ANTENNA",
			homeBtnP: "High Performance Antenna System",
			navBtnProducts: "PRODUKTY",
			navBtnAbout: "O NAS",
			navBtnContact: "KONTAKT",
			categoryWire: "ANTENY DRUTOWE",
			categoryVertical: "ANTENY PIONOWE",
			categoryAccessories: "AKCESORIA",
		},

		footer: {
			titleStore: "Sklep Firmowy",
			contactTitle: "Kontakt",
			aboutTitle: "O Red Antenna",
			about: "RED-ANTENNA jest marką handlową firmy ERcomER. Powstała w oparciu o wieloletnie doświadczenie, pasję i chęć tworzenia najlepszych produktów w zakresie osprzętu radiokomunikacyjnego.",
		},

		main: {
			header: "HIGH PERFORMANCE ANTENNA SYSTEM",
			headerP: "GDY LICZY SIĘ WYDAJNOŚĆ I JAKOŚĆ",
			handmadeTitle: "RĘCZNIE ROBIONE W POLSCE",
			handmadeText:
				"Rynek obecnie zalany jest produkcją masową. Przewagę naszej marce dodaje fakt, że jesteśmy manufakturą, nasze anteny wykonywane są ręcznie i każdy egzemplarz jest poddawany indywidualnym pomiarom na etapie produkcji. Oferujemy przemyślane produkty, ale jesteśmy gotowi do wykonania produktu na Twoje indywidualne zamówienie spełniający specyficzne potrzeby. Produkty wykonywane w Polsce spełniają wysokie wymagania jakościowe.",
			designTitle: "BEZKOMPROMISOWO ZAPROJEKTOWANE",
			designText:
				"Nasze anteny są zaprojektowane bez kompromisów, które często prowadzą do obniżenia jakości produktów. Już na etapie projektowania dbamy o szczegóły dotyczące używanych materiałów (tylko najwyższej jakości), rozwiązań technicznych oraz zoptymalizowanie konstrukcji pod kątem osiągnięcia możliwie największej efektywności anten. Anteny projektujemy tak, aby spełniały nasze założenia dostarczania produktów klasy high-end, tj. najwyższej jakości. Bez oszczędzania, bez kompromisów.",

			effectivenessTitle: "POTWIERDZONA EFEKTYWNOŚĆ",

			effectiveness:
				"Nasze anteny projektowane są w oparciu o wiedzę specjalistyczną oraz duże doświadczenie zawodowe. Wykorzystujemy także specjalistyczne oprogramowanie do modelowania anten. Jednak rzeczywistą efektywność przede wszystkim potwierdzają nasze testy praktyczne pomiaru gęstości pola elektromagnetycznego oraz praktyczne testy pomiaru siły sygnału prowadzone z wykorzystaniem sieci beaconów WSPR. Odbiorniki WSPR rozlokowane na całym świecie raportują rzeczywisty pomiar siły odbieranego sygnału. Z pewnością też efektywność naszych anten potwierdzają doskonałe opinie i liczne rekomendacje ze strony użytkowników naszych anten.",
			aboutTitle: "NASZA MISJA",
			aboutText:
				"Antena jest najważniejszym elementem, mających wpływ na zasięg każdego systemu nadawczo-odbiorczego. Naszym celem jest tworzenie bezkompromisowych anten, optymalnie zaprojektowanych, cechujących się najlepszymi parametrami i najwyższą jakością wykonania. Osiągnęliśmy go poprzez odpowiedni dobór elementów składowych, szereg testów praktycznych i wytrzymałościowych oraz pomiarów. Bazujemy na rzetelnych opracowaniach naukowych, eksperymentach wielu radioamatorów oraz przede wszystkim własnych wieloletnich doświadczeniach w budowie systemów antenowych i pracy na pasmach krótkofalowych. Dlatego też nasze anteny wyprzedzają pod wieloma względami konkurencyjne produkty dostępne na rynku i tworzą ekskluzywną linię anten wysokiej klasy (tzw. High End)",
		},

		aboutSection: {
			title: "Łączność to nasza pasja",
			text: "Historia naszej marki rozpoczęła się kilka lat temu z potrzeby dostarczenia anten najwyższej jakości, zarówno pod kątem jakości wykonania, jak i dobrze przemyślanej i optymalnej konstrukcji, która spełniłaby wysoko postawione wymagania. Mając odpowiednie możliwości techniczne naszego serwisu i wiedzę specjalistyczną postanowiliśmy rozpocząć produkcją produktów klasy high end, tj. najwyższej jakości, z dbałością faktycznie o każdy detal. W odróżnieniu od innych marek, wprowadziliśmy zasadę rzetelnego informowania o parametrach pracy anten. Dla przykładu - zamiast maksymalnej chwilowej przenoszonej mocy, prowadzącej do uszkodzenia anteny (jako podaje większość innych producentów), my informujemy o maksymalnej mocy pracy anteny (tj. maksymalnej mocy promieniowania w sposób ciągły przy której nie ulegają pogorszeniu jej osiągi), a tym samym maksymalna granica wytrzymałości anteny jest dużo większa. Tak samo dużą wagę przykładamy do wykonywania rzeczywistych pomiarów wykonanych transformatorów antenowych (w odróżnieniu od masowej produkcji, gdzie pomija się rzeczywiste pomiary poszczególnych egzemplarzy). Naszym głównym celem jest zatem budowanie marki produktów klasy premium (których często brakuje w tym segmencie rynku).",
			wsrp: "Nasze anteny testowane są pod kątem faktycznej efektywności wykorzystując rzetelne raporty WSPR. Stacje odbiorcze rozlokowane są na całym świecie i przekazują dokładny poziom siły odbieranego sygnału (w jednostkach dBm). Korzystamy z tego systemu optymalizując projekty i konstrukcje naszych anten.",
		},
		contactSection: {
			form: "Przejdź do formularza",
			formLink: "https://www.ercomer.pl/pl/contact",
			formTitle: "Formularz kontaktowy",
		},

		products: {
			common: {
				bandsTitle: "Pasma pracy:",
				spanTitle: "Rozpiętość anteny:",
				weightTitle: "Waga:",
				rangeTitle: "Szerokość pracy dla pasma dolnego (SWR 2.0):",
				swrTitle: "Maksymalny SWR w pozostałych pasmach:",
				powerTitle: "Przenoszona moc:",
				sizeTitle: "Wymiary baluna (mm, bez zaczepów):",
				MiniTunerSizeTitle: "Wymiary tunera (mm, bez zaczepów):",
				connectors: "Złącza:",
				coreTitle: "Wielkość rdzenia:",
				windingsTitle: "Uzwojenia:",
				antennaWireTitle: "Linka antenowa:",
				wireTitle: "Linka mocująca:",
				linkTitle: "Sklep",
			},

			wire: {
				common: {
					title: "ANTENY DRUTOWE",
					description:
						"Anteny typu drutowego to popularne rozwiązanie do pracy w szczególności na pasma fal krótkich. Z uwagi na często znaczną długość promiennika zapewniają bardzo dobrą efektywność dla niskich częstotliwości. Instalowane są zazwyczaj w polaryzacji poziomej, skośnej lub jako odwrócone V. Dostępne są konstrukcje o zróżnicowanej długości oraz charakterystyce promieniowania. Jednym z najpopularniejszych w tej grupie anten jest seria Red-Fed.",
				},
				redFed: {
					common: {
						series: "Red - Fed",
						description: "Anteny typu EFHW (End Fed Half Wire)",
						descriptionPage: "",
					},

					mini: {
						description:
							"Antena przeznaczona do pracy w warunkach terenowych i podczas wędrówek. Charakteryzuje się niewielkimi rozmiarami po złożeniu oraz niewielką wagą, co jest nie do przecenienia w trakcie pieszych wypraw terenowych. Taka antena zmieści się w stanie złożonym nawet do kieszeni kurtki. Wersja Mini doskonale nadają się do szybkich instalacji, robionych z biegu, rozkładanych na kilka godzin, w warunkach nie wymagających długotrwałego zawieszenia oraz w miejscach nie narażonych na działanie ekstremalnych warunków pogodowych (wiatr, szadź).",
						model: "Red-Fed Mini",
						range: "około 80kHz",
						swr: "<2.0",
						ssb: "SSB 40W",
						cw: "CW 30W",
						digi: "DIGI 20W",
						size: "51x49x36",
						feeder: "fider BNC",
						antenna: "antena 2x M3",
						core: "Amidon FT82",
						windings: "drut emaliowany DNE 0.6mm (balun i cewka)",
						antennaWire: "linka miedziana Cu 0.5mm",
						wire: "2x 10m PE 2mm",
						long: {
							model: "Red-Fed Mini 80-10 ",
							bands: "80m, 40m, 20m, 15m, 10m",
							span: "około 23m",
							weight: "360g",
							storeLink:
								"https://www.ercomer.pl/pl/p/Antena-Red-Fed-Mini-80-10/2668",
						},
						short: {
							model: "Red-Fed Mini 40-10 ",
							bands: "40m, 20m, 10m",
							span: "około 12m",
							weight: "260g",
							storeLink:
								"https://www.ercomer.pl/pl/p/Antena-Red-Fed-Mini-40-10/2669",
						},
						max: {
							description:
								"Antena przeznaczona do pracy w warunkach terenowych i podczas wędrówek. Charakteryzuje się niewielkimi rozmiarami po złożeniu oraz niewielką wagą, co jest nie do przecenienia w trakcie pieszych wypraw terenowych. Taka antena zmieści się w stanie złożonym nawet do kieszeni kurtki. Wersja Mini doskonale nadają się do szybkich instalacji, robionych z biegu, rozkładanych na kilka godzin, w warunkach nie wymagających długotrwałego zawieszenia oraz w miejscach nie narażonych na działanie ekstremalnych warunków pogodowych (wiatr, szadź).",
							model: "Red-Fed Mini 80 MAX",
							bands: "80m",
							span: "około 34m",
							weight: "300g",
							range: "około 280kHz",
							core: "RA1616",
							storeLink:
								"https://www.ercomer.pl/pl/p/Antena-Red-Fed-Mini-80-MAX/3013",
						},
					},

					midi: {
						description:
							"Antena przeznaczona głównie do wyjazdów terenowych i wakacyjnych, oferująca większą wytrzymałość mechaniczną niż wersja Mini, przez co jest bardziej odporna na trudne warunki atmosferyczne. Zastosowano tutaj balun o zwiększonej przenoszonej mocy, dzięki czemu anteny z serii Midi nadają się do pracy ze standardowymi transceiverami KF.",
						model: "Red-Fed Midi",
						range: "około 80kHz",
						swr: "<2.0",
						ssb: "SSB 150W",
						cw: "CW 100W",
						digi: "DIGI 75W",
						size: "50x70x36",
						feeder: "fider SO239 (UC1, UHF)",
						antenna: "antena 2x M4",
						core: "Amidon FT140",
						windings: "drut emaliowany DNE 1.0mm (balun i cewka)",
						antennaWire: "linka miedziana Cu 1.0mm",
						wire: "2x 10m PE 3mm",
						long: {
							model: "Red-Fed Midi 80-10",
							bands: "80m, 40m, 20m, 15m, 10m",
							span: "około 23m",
							weight: "740g",
							storeLink:
								"https://www.ercomer.pl/pl/p/Antena-Red-Fed-Midi-80-10/2666",
						},
						short: {
							model: "Red-Fed Midi 40-10",
							bands: "40m, 20m, 10m",
							span: "około 12m",
							weight: "530g",
							storeLink:
								"https://www.ercomer.pl/pl/p/Antena-Red-Fed-Midi-40-10/2667",
						},
					},

					standard: {
						description:
							"Antena do zastosowań sezonowych, takich jak dłuższe wyjazdy wakacyjne, obozy czy na działce rekreacyjnej, wszędzie tam gdzie zaistnieje potrzeba pracy przez np. sezon letni i mamy możliwość pracy porównywalnej z domowym QTH. Użyty w antenie balun z serii Standard pozwala na swobodą pracę z seryjnymi transceiverami KF oraz z małymi wzmacniaczami mocy.",
						model: "Red-Fed Standard",
						range: "około 80kHz",
						swr: "<2.0",
						ssb: "SSB 400W",
						cw: "CW 300W",
						digi: "DIGI 200W",
						size: "74x89x41",
						feeder: "fider SO239 (UC1, UHF)",
						antenna: "antena 2x M5",
						core: "Amidon FT240",
						windings:
							"drut emaliowany DN2E 1.6mm (balun) i 1.0mm (cewka)",
						antennaWire: "linka miedziana Cu 1.5mm",
						wire: "2x 10m PE 3mm",
						long: {
							model: "Red-Fed Standard 80-10",
							bands: "80m, 40m, 20m, 15m, 10m",
							span: "około 23m",
							weight: "1050g",
							storeLink:
								"https://www.ercomer.pl/pl/p/Antena-Red-Fed-Standard-80-10-/2385",
						},
						short: {
							model: "Red-Fed Standard 40-10",
							bands: "40m, 20m, 10m",
							span: "około 12m",
							weight: "710g",
							storeLink:
								"https://www.ercomer.pl/pl/p/Antena-Red-Fed-Standard-40-10/2384",
						},
					},

					hd: {
						description:
							"Antena o podwyższonej wytrzymałości mechanicznej, dzięki czemu doskonale sprawdzą się jako cało sezonowe anteny stacjonarne. Zostały one oparte na balunach z serii Standard i w związku z tym przenoszą takie same moce jak Red-Fed Standard. Wzmocnieniu jednak uległa konstrukcja mechaniczna, dzięki czemu antena może być używana przez cały rok, bez obaw o zerwanie pod ciężarem śniegu czy szadzi.",
						model: "Red-Fed HD",
						range: "około 80khz",
						swr: "<2.0",
						ssb: "SSB 400W",
						cw: "CW 300W",
						digi: "DIGI 200W",
						size: "74x89x41",
						feeder: "fider SO239 (UC1, UHF)",
						antenna: "antena 2x M5",
						core: "Amidon FT240",
						windings: "drut emaliowany DN2E 1.6mm (balun i cewka)",
						antennaWire: "linka miedziana Cu 2.5mm",
						wire: "2x 10m PE 4mm",
						long: {
							model: "Red-Fed HD 80-10",
							bands: "80m, 40m, 20m, 15m, 10m",
							span: "około 23m",
							weight: "1470g",
							storeLink:
								"https://www.ercomer.pl/pl/p/Antena-Red-Fed-HD-80-10-/2387",
						},
						short: {
							model: "Red-Fed HD 40-10",
							bands: "40m, 20m, 10m",
							span: "około 12m",
							weight: "1120g",
							storeLink:
								"https://www.ercomer.pl/pl/p/Antena-Red-Fed-HD-40-10-/2386",
						},
					},
					extreme: {
						description:
							"Anteny Red-Fed Short Extreme są antenami o podwyższonej wytrzymałości, dzięki czemu doskonale sprawdzą się jako cało sezonowe anteny stacjonarne. Wzmocnieniu uległa konstrukcja mechaniczna, dzięki czemu antena może być używana przez cały rok, bez obaw o zerwanie pod ciężarem śniegu czy szadzi. arze M5, co zapewnia odpowiednią wytrzymałość mechaniczną oraz odporność na czynniki środowiskowe. W tym przypadku w środowiskach nieagresywnych chemicznie trwałość takiego osprzętu obliczana jest na około 25 lat.",
						model: "Red-Fed Extreme",
						range: "około 300kHz",
						swr: "<2.0",
						ssb: "SSB 400W",
						cw: "CW 300W",
						digi: "DIGI 200W",
						size: "74x89x41",
						feeder: "fider SO239 (UC1, UHF)",
						antenna: "antena 2x M5",
						core: "Amidon FT240",
						windings:
							"drut podwójnie emaliowany DN2E 1.6mm (rdzeń i cewka)",
						antennaWire: "linka stalowa 1.5mm",
						wire: "2x 10m PE 4mm",
						long: {
							model: "Red-Fed 80-10 Full Extreme",
							bands: "80m, 40m, 20m, 15m, 10m",
							span: "około 39m",
							weight: "1470g",
							storeLink:
								"https://www.ercomer.pl/pl/p/Red-Fed-80-10-Full-Extreme/3553",
						},
						short: {
							model: "Red-Fed 80-10 Short Extreme",
							bands: "80m, 40m, 20m, 15m, 10m",
							span: "około 23m",
							weight: "około 1600g",
							storeLink:
								"https://www.ercomer.pl/pl/p/Red-Fed-80-10-Short-Extreme/3580",
						},
					},
				},
				redDipole: {
					common: {
						series: "Red - Dipole",
						description: "Anteny typu dipol",
						descriptionPage: "",
					},
					mini: {
						description:
							"Antena D80mini jest anteną typowo wyprawową, której konstrukcja zoptymalizowana została pod kątem wagi oraz zajmowanego miejsca w ekwipunku wyprawowym. Dodatkowo po zastosowaniu tunera antenowego, pozwala na pracę na paśmie amatorskim 80m.",
						model: "Red-Dipole D80mini",
						bands: "80m, 40m-10m ze skrzynką antenową",
						span: "około 39m",
						weight: "około 600g",
						size: "51x49x36",
						range: "",
						swr: "<2.0",
						ssb: "SSB 40W",
						cw: "CW 30W",
						digi: "DIGI 20W",
						feeder: "fider BNC",
						antenna: "antena 2x M4",
						core: "Amidon FT82",
						windings: "drut emaliowany DNE 0.6mm (balun i cewka)",
						antennaWire: "linka miedziana Cu 0.5mm",
						wire: "2x 10m PE 2mm",
						storeLink:
							"https://www.ercomer.pl/pl/p/Antena-Red-Dipol-D80mini/2556",
					},
					midi: {
						description:
							"Antena D80Midi jest anteną typowo terenową, przeznaczoną głównie na dłuższe wyjazdy. Można ją bezproblemowo użytkować np. przez cały sezon letni na działce. Zachowuje przy tym na tyle małe gabaryty po złożeniu, że z łatwością znajdzie się na nią miejsce w wyprawowym ekwipunku. Po zastosowaniu tunera antenowego, pozwala na pracę na paśmie amatorskim 80m.",
						model: "Red-Dipole D80midi",
						bands: "80m, 40m-10m ze skrzynką antenową",
						span: "około 39m",
						weight: "około 1200g",
						size: "50x70x36",
						range: "",
						swr: "<2.0",
						ssb: "SSB 150W",
						cw: "CW 100W",
						digi: "DIGI 75W",
						feeder: "fider SO239 (UC1, UHF)",
						antenna: "antena 2x M5",
						core: "Amidon FT140",
						windings: "drut emaliowany DNE 1.0mm (balun i cewka)",
						antennaWire: "linka miedziana Cu 1.0mm",
						wire: "2x 10m PE 3mm",
						storeLink:
							"https://www.ercomer.pl/pl/p/Antena-Red-Dipol-D80midi/2555",
					},
					standard: {
						description:
							"Antena D80STD jest przeznaczona głównie na dłuższe wyjazdy stacjonarne, gdzie wielkość anteny w trakcie transportu czy jej ciężar nie gra już tak dużej roli, a większe znaczenie zaczyna mieć kwestia wytrzymałości mechanicznej. Przeznaczona jest do współpracy ze standardowymi transceiverami KF o mocy 100W czy 200W i posiadający odpowiedni zapas przenoszonej mocy, nawet w przypadku emisji cyfrowych.",
						model: "Red-Dipole D80STD",
						bands: "80m, 40m-10m ze skrzynką antenową",
						span: "około 39m",
						weight: "około 1900g",
						size: "74x89x41",
						range: "",
						swr: "<2.0",
						ssb: "SSB 400W",
						cw: "CW 300W",
						digi: "DIGI 200W",
						feeder: "fider SO239 (UC1, UHF)",
						antenna: "antena 2x M5",
						core: "Amidon FT240",
						windings:
							"drut emaliowany DN2E 1.6mm (balun) i 1.0mm (cewka)",
						antennaWire: "linka miedziana Cu 1.5mm",
						wire: "2x 10m PE 3mm",
						storeLink:
							"https://www.ercomer.pl/pl/p/Antena-Red-Dipol-D80STD/2546",
					},
					hd: {
						description:
							"Wersja HD (Heavy Duty) jest wersją przeznaczoną do zastosowań przede wszystkim stacjonarnych, gdzie odpowiednia wytrzymałość mechaniczna anteny nie musi być kompromisem w stosunku do jej ciężaru czy wielkości po złożeniu.",
						model: "Red-Dipole D80HD",
						bands: "80m, 40m-10m ze skrzynką antenową",
						span: "około 39m",
						weight: "około 1700g",
						size: "74x89x41",
						range: "",
						swr: "<2.0",
						ssb: "SSB 400W",
						cw: "CW 300W",
						digi: "DIGI 200W",
						feeder: "fider SO239 (UC1, UHF)",
						antenna: "antena 2x M5",
						core: "Amidon FT240",
						windings: "drut emaliowany DN2E 1.6mm (balun i cewka)",
						antennaWire: "linka miedziana Cu 2.5mm",
						wire: "2x 10m PE 4mm",
						storeLink:
							"https://www.ercomer.pl/pl/p/Antena-Red-Dipol-D80HD/2543",
					},
					hd600: {
						description:
							"Wersja HD 600W+ jest wersją przeznaczoną do zastosowań przede wszystkim stacjonarnych, gdzie odpowiednia wytrzymałość mechaniczna anteny nie musi być kompromisem w stosunku do jej ciężaru czy wielkości po złożeniu. Balun tej anteny wykonany jest na dwóch rdzeniach Amidon FT240, których wymiary gwarantują bezproblemową pracę z mocami 500W-600W.",
						model: "Red-Dipole D80HD 600W+",
						bands: "80m, 40m-10m ze skrzynką antenową",
						span: "około 39m",
						weight: "około 1900g",
						size: "74x89x41",
						range: "",
						swr: "<2.0",
						ssb: "SSB: 1500W (160m-15m) i 1200W (12m-10m)",
						cw: "CW: 1000W (160m-15m) i 800W (12m-10m)",
						digi: "DIGI: 600W (160m-15m) i 500W (12m-10m)",
						feeder: "fider SO239 (UC1, UHF)",
						antenna: "antena 2x M5",
						core: "2x Amidon FT240",
						windings: "drut emaliowany DN2E 1.6mm (balun i cewka)",
						antennaWire: "linka miedziana Cu 2.5mm",
						wire: "2x 10m PE 4mm",
						storeLink:
							"https://www.ercomer.pl/pl/p/Antena-Red-Dipol-D80HD-600W-/2544",
					},
					hd1500: {
						description:
							"Wersja HD 1500W+ jest wersją przeznaczoną do zastosowań przede wszystkim stacjonarnych, gdzie odpowiednia wytrzymałość mechaniczna anteny nie musi być kompromisem w stosunku do jej ciężaru czy wielkości po złożeniu. Balun tej anteny wykonany jest na trzech rdzeniach Amidon FT240, których wymiary gwarantują bezproblemową pracę z większością wzmacniaczy mocy PA",
						model: "Red-Dipol D80HD 1500W+",
						bands: "80m, 40m-10m ze skrzynką antenową",
						span: "około 39m",
						weight: "około 1900g",
						size: "74x89x41",
						range: "",
						swr: "<2.0",
						ssb: "SSB: 3500W (160m-15m) i 3000W (12m-10m)",
						cw: "CW: 2500W (160m-15m) i 2200W (12m-10m)",
						digi: "DIGI: 1500W (160m-15m) i 1200W (12m-10m)",
						feeder: "fider SO239 (UC1, UHF)",
						antenna: "antena 2x M5",
						core: "3x Amidon FT240",
						windings: "drut emaliowany DN2E 1.6mm (balun i cewka)",
						antennaWire: "linka miedziana Cu 2.5mm",
						wire: "2x 10m PE 4mm",
						storeLink:
							"https://www.ercomer.pl/pl/p/Antena-Red-Dipol-D80HD-1500W-/2545",
					},
				},
				redWire: {
					common: {
						series: "Red - Wire",
						description: "Anteny typu long-wire",
						descriptionPage: "",
					},
					mini: {
						description:
							"Antena typowo wyprawowa, której konstrukcja zoptymalizowana została pod kątem wagi oraz zajmowanego miejsca w ekwipunku wyprawowym. Doskonale nadaje się do szybkich instalacji, robionych z biegu, rozkładanych na kilka godzin, w warunkach nie wymagających długotrwałego zawieszenia i w miejscach nie narażonych na działanie ekstremalnych warunków pogodowych (wiatr, szadź).",
						model: "Red-Wire Mini",
						range: "",
						swr: "<2.0",
						ssb: "SSB 40W",
						cw: "CW 30W",
						digi: "DIGI 20W",
						size: "51x49x36",
						feeder: "fider BNC",
						antenna: "antena 2x M4",
						core: "Amidon FT82",
						windings: "drut emaliowany DNE 0.6mm (balun i cewka)",
						antennaWire: "linka miedziana Cu 0.5mm",
						wire: "2x 10m PE 2mm",
						long: {
							model: "Red-Wire W38mini",
							bands: "80m-10m ze skrzynką antenową",
							span: "38m",
							weight: "370g",
							storeLink:
								"https://www.ercomer.pl/pl/p/Antena-Red-Wire-W38mini/2558",
						},
						short: {
							model: "Red-Wire W16mini",
							bands: "80m-10m ze skrzynką antenową",
							span: "16m",
							weight: "około 250g",
							storeLink:
								"https://www.ercomer.pl/pl/p/Antena-Red-Wire-W16mini/2557",
						},
					},
					midi: {
						description:
							"Antena przeznaczona głównie na dłuższe wyjazdy terenowe. Dzięki większej wytrzymałości mechanicznej niż modele Red-Wire Mini, można ją użytkować bezproblemowo np. przez cały sezon letni na działce. Zachowuje przy tym na tyle małe gabaryty po złożeniu, że z łatwością znajdzie się na nią miejsce w wyprawowym ekwipunku.",
						model: "Red-Wire Midi",
						range: "",
						swr: "<2.0",
						ssb: "SSB 150W",
						cw: "CW 100W",
						digi: "DIGI 75W",
						size: "50x70x36",
						feeder: "fider SO239 (UC1, UHF)",
						antenna: "antena 2x M5",
						core: "Amidon FT140",
						windings: "drut emaliowany DNE 1.0mm (balun i cewka)",
						antennaWire: "linka miedziana Cu 1.0mm",
						wire: "2x 10m PE 3mm",
						long: {
							model: "Red-Wire W38midi",
							bands: "80m, 40m-10m ze skrzynką antenową",
							span: "38m",
							weight: "około 700g",
							storeLink:
								"https://www.ercomer.pl/pl/p/Antena-Red-Wire-W38midi/2560",
						},
						short: {
							model: "Red-Wire W16midi",
							bands: "80m, 40m-10m ze skrzynką antenową",
							span: "16m",
							weight: "około 500g",
							storeLink:
								"https://www.ercomer.pl/pl/p/Antena-Red-Wire-W16midi/2559",
						},
					},
					standard: {
						description:
							"Przeznaczona głównie na dłuższe wyjazdy stacjonarne, gdzie wielkość anteny w trakcie transportu czy jej ciężar nie gra już tak dużej roli, a większe znaczenie zaczyna mieć kwestia wytrzymałości mechanicznej.",
						model: "Red-Wire Standard",
						range: "",
						swr: "<2.0",
						ssb: "SSB 400W",
						cw: "CW 300W",
						digi: "DIGI 200W",
						size: "74x89x41",
						feeder: "fider SO239 (UC1, UHF)",
						antenna: "antena 2x M5",
						core: "Amidon FT240",
						windings:
							"drut emaliowany DN2E 1.6mm (balun) i 1.0mm (cewka)",
						antennaWire: "linka miedziana Cu 1.5mm",
						wire: "2x 10m PE 3mm",
						long: {
							model: "Red-Wire W38STD",
							bands: "80m-10m ze skrzynką antenową",
							span: "38m",
							weight: "1100g",
							storeLink:
								"https://www.ercomer.pl/pl/p/Antena-Red-Wire-W38STD/2564",
						},
						short: {
							model: "Red-Wire W16STD",
							bands: "80m-10m ze skrzynką antenową",
							span: "16m",
							weight: "500g",
							storeLink:
								"https://www.ercomer.pl/pl/p/Antena-Red-Wire-W16STD/2562",
						},
					},
					hd: {
						description:
							"Wersja HD (Heavy Duty) jest wersją przeznaczoną do zastosowań przede wszystkim stacjonarnych, gdzie odpowiednia wytrzymałość mechaniczna anteny nie musi być kompromisem w stosunku do jej ciężaru czy wielkości po złożeniu.",
						model: "Red-Wire HD",
						range: "",
						swr: "<2.0",
						ssb: "SSB 400W",
						cw: "CW 300W",
						digi: "DIGI 200W",
						size: "74x89x41",
						feeder: "fider SO239 (UC1, UHF)",
						antenna: "antena 2x M5",
						core: "Amidon FT240",
						windings: "drut emaliowany DN2E 1.6mm (balun i cewka)",
						antennaWire: "linka miedziana Cu 2.5mm",
						wire: "2x 10m PE 4mm",
						long: {
							model: "Red-Wire W38HD",
							bands: "80m-10m ze skrzynką antenową",
							span: "38m",
							weight: "1250g",
							storeLink:
								"https://www.ercomer.pl/pl/p/Antena-Red-Wire-W38HD/2566",
						},
						short: {
							model: "Red-Wire W16HD",
							bands: "80m-10m ze skrzynką antenową",
							span: "16m",
							weight: "około 740g",
							storeLink:
								"https://www.ercomer.pl/pl/p/Antena-Red-Wire-W16HD/2565",
						},
					},
					hd600: {
						description:
							"Wersja HD (Heavy Duty) jest wersją przeznaczoną do zastosowań przede wszystkim stacjonarnych, gdzie odpowiednia wytrzymałość mechaniczna anteny nie musi być kompromisem w stosunku do jej ciężaru czy wielkości po złożeniu. Balun wykonany jest na dwóch rdzeniach Amidon FT240, których wymiary gwarantują bezproblemową pracę ze wzmacniaczami średniej mocy. Przeznaczona jest do współpracy ze wzmacniaczami PA o mocy ciągłej 500W-600W.",
						model: "Red-Wire HD 600W+",
						range: "",
						swr: "<2.0",
						ssb: "SSB: 1500W (160m-15m) i 1200W (12m-10m)",
						cw: "CW: 1000W (160m-15m) i 800W (12m-10m)",
						digi: "DIGI: 600W (160m-15m) i 500W (12m-10m)",
						size: "74x89x41",
						feeder: "fider SO239 (UC1, UHF)",
						antenna: "antena 2x M5",
						core: "2x Amidon FT240",
						windings: "drut emaliowany DN2E 1.6mm (balun i cewka)",
						antennaWire: "linka miedziana Cu 2.5mm",
						wire: "2x 10m PE 4mm",
						long: {
							model: "Red-Wire W38HD 600W+",
							bands: "80m-10m ze skrzynką antenową",
							span: "38m",
							weight: "około 980g",
							storeLink:
								"https://www.ercomer.pl/pl/p/Antena-Red-Wire-W38HD-600W-/2569",
						},
						short: {
							model: "Red-Wire W16HD 600W+",
							bands: "80m-10m ze skrzynką antenową",
							span: "16m",
							weight: "około 980g",
							storeLink:
								"https://www.ercomer.pl/pl/p/Antena-Red-Wire-W16HD-600W-/2567",
						},
					},
					hd1500: {
						description:
							"Wersja HD (Heavy Duty) jest wersją przeznaczoną do zastosowań przede wszystkim stacjonarnych, gdzie odpowiednia wytrzymałość mechaniczna anteny nie musi być kompromisem w stosunku do jej ciężaru czy wielkości po złożeniu. Balun wykonany jest na trzech rdzeniach Amidon FT240, których wymiary gwarantują bezproblemową pracę ze wzmacniaczami dużej mocy. Przeznaczona jest do współpracy ze wzmacniaczami PA dużej mocy.",
						model: "Red-Wire HD 1500W+",
						range: "",
						swr: "<2.0",
						ssb: "SSB: 3500W (160m-15m) i 3000W (12m-10m)",
						cw: "CW: 2500W (160m-15m) i 2200W (12m-10m)",
						digi: "DIGI: 1500W (160m-15m) i 1200W (12m-10m)",
						size: "74x89x41",
						feeder: "fider SO239 (UC1, UHF)",
						antenna: "antena 2x M5",
						core: "3x Amidon FT240",
						windings: "drut emaliowany DN2E 1.6mm (balun i cewka)",
						antennaWire: "linka miedziana Cu 2.5mm",
						wire: "2x 10m PE 4mm",
						long: {
							model: "Red-Wire W38HD 1500W+",
							bands: "80m-10m ze skrzynką antenową",
							span: "38m",
							weight: "około 1650g",
							storeLink:
								"https://www.ercomer.pl/pl/p/Antena-Red-Wire-W38HD-1500W-/2570",
						},
						short: {
							model: "Red-Wire W16HD 1500W+",
							bands: "80m-10m ze skrzynką antenową",
							span: "16m",
							weight: "około 1050g",
							storeLink:
								"https://www.ercomer.pl/pl/p/Antena-Red-Wire-W16HD-1500W-/2568",
						},
					},
				},
			},
			vertical: {
				common: {
					title: "ANTENY PIONOWE",
					description: "Anteny pionowe",
				},
				v3000: {
					title: "",
					titleSec: "",
					text: "",
					StoreLink: "",
					StoreLinkSec: "",
				},
				p2000: {
					title: "",
					titleSec: "",
					text: "",
					StoreLink: "",
					StoreLinkSec: "",
				},
				b1000: {
					title: "",
					titleSec: "",
					text: "",
					StoreLink: "",
					StoreLinkSec: "",
				},
			},
			accessories: {
				common: {
					title: "AKCESORIA",
					description: "Akcesoria antenowe",
				},
				miniTuner: {
					common: {
						series: "Mini Tuner",
						description:
							"Ultra mały tuner dla anten typu EFHW (End Fed Half Wire)",
					},
					long: {
						description:
							"Ultra mały i lekki tuner dla anteny typu EFHW (End Fed Half Wire) ze wskaźnikiem SWR. Do skuteczngo dostrojenia anteny nie jest wymagany miernik SWR w transceiverze. Zapewnia dostrojenie półfalowgo promiennika (linka antenowa o długości połowy fali danego pasma) do rezonansu w pasmach 40m/30m/20m/15m. Nie uszkodzisz stopnia końcowego mocy transceivera przy niedopasowanej antenie - układ tunera ma wbudowane sztuczne ociążenie, wykorzystywane podczas strojenia promiennika (przełącznik strojenie/praca). Sygnalizacja dostrojenia za pomocą czerwonej diody LED. Wersja wyposażona we wtyk BNC, umożliwiająca połączenie tunera bezpośrednio z transceiverem bez użycia kabla koncentrycznego.",

						model: "Mini-Tuner wtyk BNC",
						weight: "70g",
						power: "10W P.E.P",
						size: "60x40x30",
						feeder: "wtyk BNC",
						antenna:
							"2x banan (dla promiennika czerwone, dla przeciwwagi czarne)",
						storeLink:
							"https://www.ercomer.pl/pl/p/Red-Antenna-EFHW-Mini-Tuner-wtyk-BNC/3241",
					},
					short: {
						description:
							"Ultra mały i lekki tuner dla anteny typu EFHW (End Fed Half Wire) ze wskaźnikiem SWR. Do skuteczngo dostrojenia anteny nie jest wymagany miernik SWR w transceiverze. Zapewnia dostrojenie półfalowgo promiennika (linka antenowa o długości połowy fali danego pasma) do rezonansu w pasmach 40m/30m/20m/15m. Nie uszkodzisz stopnia końcowego mocy transceivera przy niedopasowanej antenie - układ tunera ma wbudowane sztuczne ociążenie, wykorzystywane podczas strojenia promiennika (przełącznik strojenie/praca). Sygnalizacja dostrojenia za pomocą czerwonej diody LED.",
						model: "Mini-Tuner gniazdo BNC",
						weight: "70g",
						power: "10W P.E.P",
						size: "60x40x30",
						feeder: "gniazdo BNC",
						antenna:
							"2x banan (dla promiennika czerwone, dla przeciwwagi czarne)",
						storeLink:
							"https://www.ercomer.pl/pl/p/Red-Antenna-EFHW-Mini-Tuner-gniazdo-BNC/3220",
					},
				},
				redChoke: {
					common: {
						series: "Balun Red-Choke",
						description: "Balun typu choker",
						descriptionPage:
							"Praktycznie każdy typ anteny zasilanej kablem koncentrycznym w miejscu podłączenia anteny powinien posiadać choke balun. Zastosowano tu zupełnie inne podejście niż klasyczne nawinięcie przewodu koncentrycznego na rdzenie ferrytowe, Choke-balun składa się z dwóch uzwojeń bifilarnych.",
						weight: "...g",
						power: "max 1.5KW",
						size: "170x75x55",
						sockets: "SO239 (UC1, UHF)",
						cable: "Wtyk PL259 (UC1, UHF) + 60cm RG-213U",
						range: "1-30MHz",
						storeLink:
							"https://www.ercomer.pl/pl/p/RED-ANTENA-balun-pradowy-Choke-Balun-1.5kW/3478",
					},
				},
				redMount: {
					common: {
						series: "Uchwyt Red-Mount",
						description: "Aluminiowy uchwyt do anten pionowych",
						descriptionPage:
							"Uchwyt wykonany jest z anodowanego aluminium, umożliwia montaż anteny z gwintem 3/8 cala i bezpośrednie wpięcie szpili w grunt (trawnik). Szpila zapewnia bardzo szybką instalację anteny w terenie, a dodatkowo zapewnia dobre uziemienie, wymagane dla anten typu whip. Szpila zakończona jest gwintem z nakrętką motylkową do wygodnego podłączenia dodatkowych radialsów. Do podłączenia kabla koncentrycznego uchwyt posiada gniazdo SO239 (UC1).",
						storeLink:
							"https://www.ercomer.pl/pl/p/Uchwyt-38-do-anten-Ampro-/2984",
					},
				},
				redCon: {
					common: {
						series: "Zestaw złączy Red-Con",
						description: "Uniwersalny zestaw przejściówek",
						connectorsTitle: "Zestaw zawiera następujące elementy:",
					},
					long: {
						model: "Red-Con 01",
						description:
							"Uniwersalny zestaw przejściówek (redukcji) pomiędzy najpopularniejszymi typami złączy stosowanych w radiokomunikacji. Niezbędnik do podłączania różnych typów anten i kabli do radiotelefonów i analizatorów. W zestawie poręczne pudełko do przechowywania i wygodnego przenoszenia wszystkich elementów.",
						connectors: [
							"1x przejściówka wtyk BNC <-> gniazdo UHF SO239 (UC1)",
							"1x przejściówka wtyk N <-> gniazdo UHF (SO239, UC1)",
							"1x przejściówka BNC gniazdo <-> wtyk UHF (PL259, UC1)",
							"1x przejściówka wtyk UHF (PL259, UC1) <-> gniazdo N",
							"1x przejściówka wtyk N -> wtyk PL259",
							"1x przejściówka wtyk Mini-UHF -> gniazdo SO239 (UC1, UHF)",
							"1x przejściówka wtyk Mini-UHF -> gniazdo BNC",
							"1x przejściówka wtyk SMA-M - gniazdo UHF (SO239, UC1)",
							"1x przejściówka wtyk BNC <-> gniazdo SMA-F",
							"1x przejściówka wtyk SMA-M <-> gniazdo BNC",
							"1x przejściówka wtyk N <-> gniazdo BNC",
							"1x przejściówka wtyk N <-> wtyk SMA-F",
							"1x łącznik gniazdo UHF <-> gniazdo UHF (SO239, UC1)",
							"1x łącznik gniazdo SMA-F -> SMA-F",
							"1x łącznik wtyk SMA-M <-> wtyk SMA-M",
							"1x łącznik gniazdo BNC <-> gniazdo BNC",
							"1x łącznik gniazdo SO239 -> wtyk PL259 (UC1, UHF) kątowy",
						],
						storeLink:
							"https://www.ercomer.pl/pl/p/Uniwersalny-zestaw-przejsciowek-RED-CON-01/2731",
					},
					short: {
						model: "Red-Con 02",
						description:
							"Uniwersalny zestaw przejściówek (redukcji) pomiędzy najpopularniejszymi typami złączy stosowanych w radiokomunikacji. Niezbędnik do podłączania różnych typów anten i kabli do radiotelefonów i analizatorów. W zestawie poręczne pudełko do przechowywania i wygodnego przenoszenia wszystkich elementów.",
						connectors: [
							"1mb kabel koncentryczny RG58 C/U zakończony wtykami BNC",
							"2x przejściówka wtyk PL259 (UC1, UHF) -> gniazdo BNC",
							"2x przejściówka wtyk N -> gniazdo BNC",
							"2x przejściówka gniazdo N -> gniazdo BNC",
							"2x przejściówka wtyk SMA-F -> gniazdo BNC",
							"2x Przejściówka wtyk SMA-M -> gniazdo BNC",
							"2x Łącznik gniazdo BNC -> gniazdo BNC",
							"1x łącznik wtyk BNC -> wtyk BNC",
							"1x łącznik wtyk PL259 (UC1, UHF) -> gniazdo BNC kątowy",
							"1x łącznik gniazdo BNC -> wtyk BNC kątowy",
						],
						storeLink:
							"https://www.ercomer.pl/pl/p/Uniwersalny-zestaw-przejsciowek-RED-CON-02-typu-BNC/3574",
					},
				},
				redLine: {
					common: {
						series: "Kabel Red-Line",
						descriptionPage:
							"Red-Line to wysokiej klasy przewód 50 Ω typu RG 58 dla najbardziej wymagających użytkowników takich kabli. Żyła wewnętrzna to linka bardzo precyzyjnie skręcona z drutów wykonanych z najwyższej klasy miedzi beztlenowej ( średnica zewnętrzna 0,9 mm ). Dla zasygnalizowania wysokiej jakości wykonania, bardzo dobrych parametrów oraz wyróżnienia produktu na rynku powłoka zewnętrzna tego przewodu jest nietypowa – transparentna z lekkim zabarwieniem na czerwono ( oczywiście przewód można stosować również na zewnątrz, powłoka jest odporna na promieniowanie UV ). Ekran RG 58 RED jest wykonany z bardzo gęstego oplotu ( 98% ), a druty w pasemkach oplotu mają średnicę aż 0,16 mm.",
						description: "Wysokiej klasy przewód typu RG 58",
						storeLink:
							"https://www.ercomer.pl/pl/p/Kabel-koncentryczny-RG58-RED/3565",
					},
				},
			},
		},
	},

	english: {
		common: {
			pl: false,
			storeLocation: "Bieżuńska 1/51 03-578 Warsaw",
			open: "Mon-Fri 10:00 - 18:00",
			country: "Poland",
			location: "https://maps.app.goo.gl/s7hr6nTTHfrLKx3w6",
			onlineStoreLink: "https://www.ercomer.pl/",
			phoneMain: "(+48) 22 270 12 15",
			phoneSec: "(+48) 798 792 927",
			phoneService: "(+48) 22 270 12 07",
			email: "info@ercomer.com",
			phoneMainTitle: "Primary line",
			phoneSecTitle: "Secondary line",
			phoneServiceTitle: "Production and service department",
			emailTitle: "Email",
			storeTitle: "Physical location",
			onlineStore: "Online store",
			hoursTitle: "Opening hours",
			distributorsTitle: "EU Distributors",
		},

		nav: {
			brandName: "RED-ANTENNA",
			homeBtnP: "High Performance Antenna System",
			navBtnProducts: "PRODUCTS",
			navBtnAbout: "ABOUT",
			navBtnContact: "CONTACT",
			categoryWire: "WIRE ANTENNAS",
			categoryVertical: "VERTICAL ANTENNAS",
			categoryAccessories: "ACCESSORIES",
		},

		footer: {
			titleStore: "Company store",
			contactTitle: "Contact",
			aboutTitle: "About Red Antenna",
			about: "RED-ANTENNA is a trademark of ERcomER. It was established based on years of experience, passion and desire to create the best products in the field of radio communication equipment.",
		},

		main: {
			header: "HIGH PERFORMANCE ANTENNA SYSTEM",
			headerP: "WHEN PERFORMANCE AND QUALITY MATTER",
			handmadeTitle: "HANDMADE IN POLAND",
			handmadeText:
				"The market today is flooded with mass production. The advantage of our brand is that we are a manufactory, our antennas are made by hand and each piece is individually measured at the production stage. We offer thoughtfully designed products, but we are ready to make a customized product to meet your specific needs. Products made in Poland meet high quality requirements.",
			designTitle: "DESIGNED WITHOUT CUTTING CORNERS",
			designText:
				"Our antennas are designed without compromises that often lead to lower quality products. Already at the design stage, we take care of the details of the materials used (only of the highest quality), technical solutions and optimizing the design to achieve the highest possible efficiency of the antennas. We design antennas to meet our goal of providing high-end products, i.e. the highest quality. No saving, no compromises.",

			effectivenessTitle: "PROVEN EFFECTIVENESS",

			effectiveness:
				"Our antennas are designed based on expertise and extensive professional experience. We also use specialized antenna modeling software. However, actual effectiveness is primarily confirmed by our practical tests of electromagnetic field density measurements and practical signal strength measurement tests conducted using WSPR's network of beacons. WSPR receivers deployed around the world report actual measurements of received signal strength. Certainly, the effectiveness of our antennas is also confirmed by excellent feedback and numerous recommendations from users of our antennas.",
			aboutTitle: "OUR GOAL",
			aboutText:
				"The antenna is the most important element, affecting the range of any transceiver system. Our goal is to create uncompromising antennas, optimally designed, featuring the best parameters and highest quality workmanship. We have achieved it through appropriate selection of components, a series of practical and endurance tests and measurements. We rely on reliable scientific studies, the experiments of many radio amateurs and, above all, our own many years of experience in building antenna systems and working on the shortwave bands. Therefore, our antennas are in many respects ahead of competitive products available on the market and form an exclusive line of high-end (so-called High End) antennas",
		},

		aboutSection: {
			title: "Communication is our passion",
			text: "The history of our brand began several years ago with the need to provide antennas of the highest quality, both in terms of workmanship and well thought out and optimal design that would meet the high end requirements. With the appropriate technical capabilities of our service and expertise, we decided to start producing high-end products, i.e. of the highest quality, with attention actually to every detail. Unlike other brands, we introduced the principle of providing reliable information about the working parameters of antennas. For example - instead of the maximum instantaneous transmitted power, leading to damage to the antenna (as stated by most other manufacturers), we inform about the maximum working power of the antenna (i.e. the maximum power of continuous radiation at which its performance does not deteriorate), and thus the maximum limit of durability of the antenna is much higher. We attach the same importance to taking actual measurements of the antenna transformers made (unlike mass production, where actual measurements of individual units are omitted). Our main goal, therefore, is to build a brand of premium products (which are often lacking in this market segment).",
			wsrp: "Our antennas are tested for actual effectiveness using reliable WSPR reports. Receiving stations are located around the world and transmit the exact level of received signal strength (in units of dBm). We use this system to optimize the design and construction of our antennas.",
		},
		contactSection: {
			form: "Go to form",
			formLink: "https://www.ercomer.pl/pl/contact",
			formTitle: "Contact form",
		},

		distributorCountries: [
			{
				name: "Poland",
				distributors: [
					{
						name: "ERcomER",
						url: "https://www.ercomer.pl/pl/c/Produkty-RED-ANTENNA/576",
					},
				],
			},
			{
				name: "Germany",
				distributors: [
					{
						name: "Wimo",
						url: "https://www.wimo.com/en/",
					},
				],
			},
		],

		products: {
			common: {
				bandsTitle: "Operating bands:",
				spanTitle: "Antenna span:",
				weightTitle: "Weight:",
				rangeTitle: "Working width for the lower band (SWR 2.0):",
				swrTitle: "Maximum SWR in other bands:",
				powerTitle: "Transferred power:",
				sizeTitle: "Dimensions of the balun (mm, without hooks):",
				MiniTunerSizeTitle: "Tuner dimensions (mm, without hooks):",
				connectors: "Connectors:",
				coreTitle: "Core size:",
				windingsTitle: "Windings:",
				antennaWireTitle: "Antenna wire:",
				wireTitle: "Fastening wire:",
				linkTitle: "Where to buy",
			},

			wire: {
				common: {
					title: "WIRE ANTENNAS",
					description:
						"Popular solution for short-wave bands in particular. Due to the often considerable length of the radiator, they provide very good efficiency for low frequencies. They are usually installed in horizontal polarization, oblique polarization or as an inverted V. Designs are available with varying lengths and radiation characteristics. One of the most popular in this group of antennas is the Red-Fed series.",
				},
				redFed: {
					common: {
						series: "Red - Fed",
						description: "EFHW antennas (End Fed Half Wire)",
						descriptionPage: "",
					},

					mini: {
						description:
							"The antenna is designed for use in off-road and hiking conditions. It is characterized by its small size when folded and light weight, which is invaluable when hiking off-road. Such an antenna will fit folded even into a jacket pocket. Mini versions are ideal for quick installations, done on the run, unfolded for a few hours, in conditions that do not require long-term suspension and in places not exposed to extreme weather conditions (wind, rime).",
						model: "Red-Fed Mini",
						range: "around 80kHz",
						swr: "<2.0",
						ssb: "SSB 40W",
						cw: "CW 30W",
						digi: "DIGI 20W",
						size: "51x49x36",
						feeder: "feeder BNC",
						antenna: "antenna 2x M3",
						core: "Amidon FT82",
						windings: "enameled wire DNE 0.6mm (core and coil)",
						antennaWire: "copper wire Cu 0.5mm",
						wire: "2x 10m PE 2mm",
						long: {
							model: "Red-Fed Mini 80-10 ",
							bands: "80m, 40m, 20m, 15m, 10m",
							span: "around 23m",
							weight: "360g",
							storeLink: "/distributors#",
						},
						short: {
							model: "Red-Fed Mini 40-10 ",
							bands: "40m, 20m, 10m",
							span: "around 12m",
							weight: "260g",
							storeLink: "/distributors#",
						},
						max: {
							description:
								"The antenna is designed for use in off-road and hiking conditions. It is characterized by its small size when folded and light weight, which is invaluable when hiking off-road. Such an antenna will fit folded even into a jacket pocket. Mini versions are ideal for quick installations, done on the run, unfolded for a few hours, in conditions that do not require long-term suspension and in places not exposed to extreme weather conditions (wind, rime).",
							model: "Red-Fed Mini 80 MAX",
							bands: "80m",
							span: "around 34m",
							weight: "300g",
							range: "around 280kHz",
							core: "RA1616",
							storeLink: "/distributors#",
						},
					},

					midi: {
						description:
							"This antenna is designed mainly for field trips and vacations, offering greater mechanical strength than the Mini version, making it more resistant to harsh weather conditions. It uses a balun with increased transmitted power, making the Midi series antennas suitable for use with standard KF transceivers.",
						model: "Red-Fed Midi",
						range: "around 80kHz",
						swr: "<2.0",
						ssb: "SSB 150W",
						cw: "CW 100W",
						digi: "DIGI 75W",
						size: "50x70x36",
						feeder: "feeder SO239 (UC1, UHF)",
						antenna: "antenna 2x M4",
						core: "Amidon FT140",
						windings: "enameled wire DNE 1.0mm (core and coil)",
						antennaWire: "copper wire Cu 1.0mm",
						wire: "2x 10m PE 3mm",
						long: {
							model: "Red-Fed Midi 80-10",
							bands: "80m, 40m, 20m, 15m, 10m",
							span: "around 23m",
							weight: "740g",
							storeLink: "/distributors#",
						},
						short: {
							model: "Red-Fed Midi 40-10",
							bands: "40m, 20m, 10m",
							span: "around 12m",
							weight: "530g",
							storeLink: "/distributors#",
						},
					},

					standard: {
						description:
							"Antenna for seasonal use, such as longer holiday trips, camps or on a recreational plot, wherever there will be a need to work through, for example, the summer season and we have the opportunity to work comparable to a home QTH. The Standard series balun used in the antenna allows free operation with serial KF transceivers and small power amplifiers.",
						model: "Red-Fed Standard",
						range: "around 80kHz",
						swr: "<2.0",
						ssb: "SSB 400W",
						cw: "CW 300W",
						digi: "DIGI 200W",
						size: "74x89x41",
						feeder: "feeder SO239 (UC1, UHF)",
						antenna: "antenna 2x M5",
						core: "Amidon FT240",
						windings:
							"enameled wire DN2E 1.6mm (core) i 1.0mm (coil)",
						antennaWire: "copper wire Cu 1.5mm",
						wire: "2x 10m PE 3mm",
						long: {
							model: "Red-Fed Standard 80-10",
							bands: "80m, 40m, 20m, 15m, 10m",
							span: "around 23m",
							weight: "1050g",
							storeLink: "/distributors#",
						},
						short: {
							model: "Red-Fed Standard 40-10",
							bands: "40m, 20m, 10m",
							span: "around 12m",
							weight: "710g",
							storeLink: "/distributors#",
						},
					},

					hd: {
						description:
							"Antennas with increased mechanical strength, making them ideal for use as all-season stationary antennas. They are based on Standard Series baluns and therefore carry the same power as Red-Fed Standard. However, the mechanical structure has been strengthened, so the antenna can be used year-round without worrying about breaking under the weight of snow or rime.",
						model: "Red-Fed HD",
						range: "around 80khz",
						swr: "<2.0",
						ssb: "SSB 400W",
						cw: "CW 300W",
						digi: "DIGI 200W",
						size: "74x89x41",
						feeder: "fedder SO239 (UC1, UHF)",
						antenna: "antenna 2x M5",
						core: "Amidon FT240",
						windings: "enameled wire DN2E 1.6mm (core and coil)",
						antennaWire: "copper wire Cu 2.5mm",
						wire: "2x 10m PE 4mm",
						long: {
							model: "Red-Fed HD 80-10",
							bands: "80m, 40m, 20m, 15m, 10m",
							span: "around 23m",
							weight: "1470g",
							storeLink: "/distributors#",
						},
						short: {
							model: "Red-Fed HD 40-10",
							bands: "40m, 20m, 10m",
							span: "around 12m",
							weight: "1120g",
							storeLink: "/distributors#",
						},
					},
					extreme: {
						description:
							"Red-Fed Extreme antennas are heavy-duty antennas, making them ideal as all-season stationary antennas. The mechanical structure has been strengthened, so the antenna can be used all year round, without fear of breaking under the weight of snow or rime. arze M5, which provides adequate mechanical strength and resistance to environmental factors. In this case, in chemically non-aggressive environments, the lifespan of such equipment is calculated to be about 25 years.",
						model: "Red-Fed Extreme",
						range: "around 300kHz",
						swr: "<2.0",
						ssb: "SSB 400W",
						cw: "CW 300W",
						digi: "DIGI 200W",
						size: "74x89x41",
						feeder: "feeder SO239 (UC1, UHF)",
						antenna: "antenna 2x M5",
						core: "Amidon FT240",
						windings:
							"double-enameled wire DN2E 1.6mm (core and coil)",
						antennaWire: "steel wire 1.5mm",
						wire: "2x 10m PE 4mm",
						long: {
							model: "Red-Fed 80-10 Full Extreme",
							bands: "80m, 40m, 20m, 15m, 10m",
							span: "around 39m",
							weight: "1470g",
							storeLink: "/distributors#",
						},
						short: {
							model: "Red-Fed 80-10 Short Extreme",
							bands: "80m, 40m, 20m, 15m, 10m",
							span: "around 23m",
							weight: "around 1600g",
							storeLink: "/distributors#",
						},
					},
				},
				redDipole: {
					common: {
						series: "Red - Dipole",
						description: "Dipole antennas",
						descriptionPage: "",
					},
					mini: {
						description:
							"The D80mini antenna is a typical expedition antenna, the design of which has been optimized for weight and space occupied in expedition equipment. In addition, after using an antenna tuner, it allows operation on the amateur band 80m.",
						model: "Red-Dipole D80mini",
						bands: "80m, 40m-10m with antenna box",
						span: "around 39m",
						weight: "around 600g",
						size: "51x49x36",
						range: "",
						swr: "<2.0",
						ssb: "SSB 40W",
						cw: "CW 30W",
						digi: "DIGI 20W",
						feeder: "feeder BNC",
						antenna: "antenna 2x M4",
						core: "Amidon FT82",
						windings: "enameled wire DNE 0.6mm (core and coil)",
						antennaWire: "copper wire Cu 0.5mm",
						wire: "2x 10m PE 2mm",
						storeLink: "/distributors#",
					},
					midi: {
						description:
							"The D80Midi antenna is a typical off-road antenna, intended mainly for longer trips. It can be easily used, for example, throughout the summer season on a plot of land. At the same time it is small enough when folded that it will easily find a place for it in your expeditionary equipment. After applying the antenna tuner, it allows to work on the amateur band 80m.",
						model: "Red-Dipole D80midi",
						bands: "80m, 40m-10m with antenna box",
						span: "around 39m",
						weight: "around 1200g",
						size: "50x70x36",
						range: "",
						swr: "<2.0",
						ssb: "SSB 150W",
						cw: "CW 100W",
						digi: "DIGI 75W",
						feeder: "feeder SO239 (UC1, UHF)",
						antenna: "antenna 2x M5",
						core: "Amidon FT140",
						windings: "enameled wire DNE 1.0mm (core and coil)",
						antennaWire: "copper wire Cu 1.0mm",
						wire: "2x 10m PE 3mm",
						storeLink: "/distributors#",
					},
					standard: {
						description:
							"The D80STD antenna is intended mainly for longer stationary trips, where the size of the antenna during transport or its weight no longer plays such a big role, and the issue of mechanical strength becomes more important. It is designed to work with standard KF transceivers of 100W or 200W power, and has an adequate reserve of transmitted power, even in the case of digital emissions.",
						model: "Red-Dipole D80STD",
						bands: "80m, 40m-10m with antenna box",
						span: "around 39m",
						weight: "around 1900g",
						size: "74x89x41",
						range: "",
						swr: "<2.0",
						ssb: "SSB 400W",
						cw: "CW 300W",
						digi: "DIGI 200W",
						feeder: "feeder SO239 (UC1, UHF)",
						antenna: "antenna 2x M5",
						core: "Amidon FT240",
						windings:
							"enameled wire DN2E 1.6mm (core) i 1.0mm (coli)",
						antennaWire: "copper wire Cu 1.5mm",
						wire: "2x 10m PE 3mm",
						storeLink: "/distributors#",
					},
					hd: {
						description:
							"The HD (Heavy Duty) version is a version designed for primarily stationary applications, where adequate mechanical strength of the antenna does not have to compromise on its weight or size when folded.",
						model: "Red-Dipole D80HD",
						bands: "80m, 40m-10m with antenna box",
						span: "around 39m",
						weight: "around 1700g",
						size: "74x89x41",
						range: "",
						swr: "<2.0",
						ssb: "SSB 400W",
						cw: "CW 300W",
						digi: "DIGI 200W",
						feeder: "feeder SO239 (UC1, UHF)",
						antenna: "antenna 2x M5",
						core: "Amidon FT240",
						windings: "enameled wire DN2E 1.6mm (core and coil)",
						antennaWire: "copper wire Cu 2.5mm",
						wire: "2x 10m PE 4mm",
						storeLink: "/distributors#",
					},
					hd600: {
						description:
							"The HD 600W+ version is a version designed for primarily stationary applications, where the adequate mechanical strength of the antenna does not have to compromise on its weight or size when folded. The balun of this antenna is made on two Amidon FT240 cores, whose dimensions guarantee trouble-free operation with 500W-600W power.",
						model: "Red-Dipole D80HD 600W+",
						bands: "80m, 40m-10m with antenna box",
						span: "around 39m",
						weight: "around 1900g",
						size: "74x89x41",
						range: "",
						swr: "<2.0",
						ssb: "SSB: 1500W (160m-15m) i 1200W (12m-10m)",
						cw: "CW: 1000W (160m-15m) i 800W (12m-10m)",
						digi: "DIGI: 600W (160m-15m) i 500W (12m-10m)",
						feeder: "feeder SO239 (UC1, UHF)",
						antenna: "antenna 2x M5",
						core: "2x Amidon FT240",
						windings: "enameled wire DN2E 1.6mm (core and coil)",
						antennaWire: "copper wire Cu 2.5mm",
						wire: "2x 10m PE 4mm",
						storeLink: "/distributors#",
					},
					hd1500: {
						description:
							"The HD 1500W+ version is a version designed for primarily stationary applications, where adequate mechanical strength of the antenna does not have to compromise on its weight or size when folded. The balun of this antenna is made on three Amidon FT240 cores, whose dimensions guarantee trouble-free operation with most PA power amplifiers.",
						model: "Red-Dipol D80HD 1500W+",
						bands: "80m, 40m-10m with antenna box",
						span: "around 39m",
						weight: "around 1900g",
						size: "74x89x41",
						range: "",
						swr: "<2.0",
						ssb: "SSB: 3500W (160m-15m) i 3000W (12m-10m)",
						cw: "CW: 2500W (160m-15m) i 2200W (12m-10m)",
						digi: "DIGI: 1500W (160m-15m) i 1200W (12m-10m)",
						feeder: "feeder SO239 (UC1, UHF)",
						antenna: "antenna 2x M5",
						core: "3x Amidon FT240",
						windings: "enameled wire DN2E 1.6mm (core and coil)",
						antennaWire: "copper wire Cu 2.5mm",
						wire: "2x 10m PE 4mm",
						storeLink: "/distributors#",
					},
				},
				redWire: {
					common: {
						series: "Red - Wire",
						description: "Long-wire antennas",
						descriptionPage: "",
					},
					mini: {
						description:
							"A typical expedition antenna, the design of which has been optimized for weight and space occupied in expedition equipment.It is ideal for quick installations, done on the run, unfolded for a few hours, in conditions that do not require long-term suspension and in places not exposed to extreme weather conditions (wind, rime). PA power amplifiers.",
						model: "Red-Wire Mini",
						range: "",
						swr: "<2.0",
						ssb: "SSB 40W",
						cw: "CW 30W",
						digi: "DIGI 20W",
						size: "51x49x36",
						feeder: "feeder BNC",
						antenna: "antenna 2x M4",
						core: "Amidon FT82",
						windings: "enameled wire DNE 0.6mm (core and coil)",
						antennaWire: "copper wire Cu 0.5mm",
						wire: "2x 10m PE 2mm",
						long: {
							model: "Red-Wire W38mini",
							bands: "80m-10m with antenna box",
							span: "38m",
							weight: "370g",
							storeLink: "/distributors#",
						},
						short: {
							model: "Red-Wire W16mini",
							bands: "80m-10m with antenna box",
							span: "16m",
							weight: "around 250g",
							storeLink: "/distributors#",
						},
					},
					midi: {
						description:
							"The antenna is designed mainly for longer off-road trips.With greater mechanical strength than the Red-Wire Mini models, it can be used without problems, for example, throughout the summer season on a plot of land. At the same time it remains small enough after folding that you can easily find a place for it in your expedition equipment.",
						model: "Red-Wire Midi",
						range: "",
						swr: "<2.0",
						ssb: "SSB 150W",
						cw: "CW 100W",
						digi: "DIGI 75W",
						size: "50x70x36",
						feeder: "feeder SO239 (UC1, UHF)",
						antenna: "antenna 2x M5",
						core: "Amidon FT140",
						windings: "enameled wire DNE 1.0mm (core and coil)",
						antennaWire: "copper wire Cu 1.0mm",
						wire: "2x 10m PE 3mm",
						long: {
							model: "Red-Wire W38midi",
							bands: "80m, 40m-10m with antenna box",
							span: "38m",
							weight: "around 700g",
							storeLink: "/distributors#",
						},
						short: {
							model: "Red-Wire W16midi",
							bands: "80m, 40m-10m with antenna box",
							span: "16m",
							weight: "around 500g",
							storeLink: "/distributors#",
						},
					},
					standard: {
						description:
							"It is intended mainly for longer stationary trips, where the size of the antenna during transport or its weight no longer plays such a big role, and the issue of mechanical strength becomes more important.",
						model: "Red-Wire Standard",
						range: "",
						swr: "<2.0",
						ssb: "SSB 400W",
						cw: "CW 300W",
						digi: "DIGI 200W",
						size: "74x89x41",
						feeder: "feeder SO239 (UC1, UHF)",
						antenna: "antenna 2x M5",
						core: "Amidon FT240",
						windings:
							"enameled wire DN2E 1.6mm (core) i 1.0mm (coil)",
						antennaWire: "copper wire Cu 1.5mm",
						wire: "2x 10m PE 3mm",
						long: {
							model: "Red-Wire W38STD",
							bands: "80m-10m with antenna box",
							span: "38m",
							weight: "1100g",
							storeLink: "/distributors#",
						},
						short: {
							model: "Red-Wire W16STD",
							bands: "80m-10m with antenna box",
							span: "16m",
							weight: "500g",
							storeLink: "/distributors#",
						},
					},
					hd: {
						description:
							"The HD (Heavy Duty) version is a version designed for primarily stationary applications, where adequate mechanical strength of the antenna does not have to compromise on its weight or size when folded.",
						model: "Red-Wire HD",
						range: "",
						swr: "<2.0",
						ssb: "SSB 400W",
						cw: "CW 300W",
						digi: "DIGI 200W",
						size: "74x89x41",
						feeder: "feeder SO239 (UC1, UHF)",
						antenna: "antenna 2x M5",
						core: "Amidon FT240",
						windings: "enameled wire DN2E 1.6mm (core and coil)",
						antennaWire: "copper wire Cu 2.5mm",
						wire: "2x 10m PE 4mm",
						long: {
							model: "Red-Wire W38HD",
							bands: "80m-10m with antenna box",
							span: "38m",
							weight: "1250g",
							storeLink: "/distributors#",
						},
						short: {
							model: "Red-Wire W16HD",
							bands: "80m-10m with antenna box",
							span: "16m",
							weight: "around 740g",
							storeLink: "/distributors#",
						},
					},
					hd600: {
						description:
							"The HD (Heavy Duty) version is a version designed for primarily stationary applications, where adequate mechanical strength of the antenna does not have to compromise on its weight or size when folded. The balun is made on two Amidon FT240 cores, the dimensions of which guarantee trouble-free operation with medium-power amplifiers. It is designed to work with PA amplifiers of 500W-600W continuous power.",
						model: "Red-Wire HD 600W+",
						range: "",
						swr: "<2.0",
						ssb: "SSB: 1500W (160m-15m) i 1200W (12m-10m)",
						cw: "CW: 1000W (160m-15m) i 800W (12m-10m)",
						digi: "DIGI: 600W (160m-15m) i 500W (12m-10m)",
						size: "74x89x41",
						feeder: "feeder SO239 (UC1, UHF)",
						antenna: "antenna 2x M5",
						core: "2x Amidon FT240",
						windings: "enameled wire DN2E 1.6mm (core and coil)",
						antennaWire: "copper wire Cu 2.5mm",
						wire: "2x 10m PE 4mm",
						long: {
							model: "Red-Wire W38HD 600W+",
							bands: "80m-10m with antenna box",
							span: "38m",
							weight: "around 980g",
							storeLink: "/distributors#",
						},
						short: {
							model: "Red-Wire W16HD 600W+",
							bands: "80m-10m with antenna box",
							span: "16m",
							weight: "around 980g",
							storeLink: "/distributors#",
						},
					},
					hd1500: {
						description:
							"The HD (Heavy Duty) version is a version designed for primarily stationary applications, where adequate mechanical strength of the antenna does not have to compromise on its weight or size when folded. The balun is made on three Amidon FT240 cores, the dimensions of which guarantee trouble-free operation with high-power amplifiers. It is designed to work with high-power PA amplifiers.",
						model: "Red-Wire HD 1500W+",
						range: "",
						swr: "<2.0",
						ssb: "SSB: 3500W (160m-15m) i 3000W (12m-10m)",
						cw: "CW: 2500W (160m-15m) i 2200W (12m-10m)",
						digi: "DIGI: 1500W (160m-15m) i 1200W (12m-10m)",
						size: "74x89x41",
						feeder: "feeder SO239 (UC1, UHF)",
						antenna: "antenna 2x M5",
						core: "3x Amidon FT240",
						windings: "enameled wire DN2E 1.6mm (core and coil)",
						antennaWire: "copper wire Cu 2.5mm",
						wire: "2x 10m PE 4mm",
						long: {
							model: "Red-Wire W38HD 1500W+",
							bands: "80m-10m with antenna box",
							span: "38m",
							weight: "around 1650g",
							storeLink: "/distributors#",
						},
						short: {
							model: "Red-Wire W16HD 1500W+",
							bands: "80m-10m with antenna box",
							span: "16m",
							weight: "around 1050g",
							storeLink: "/distributors#",
						},
					},
				},
			},
			vertical: {
				common: {
					title: "VERTICAL ANTENNAS",
					description: "Vertical antennas",
				},
				v3000: {
					title: "",
					titleSec: "",
					text: "",
					StoreLink: "",
					StoreLinkSec: "",
				},
				p2000: {
					title: "",
					titleSec: "",
					text: "",
					StoreLink: "",
					StoreLinkSec: "",
				},
				b1000: {
					title: "",
					titleSec: "",
					text: "",
					StoreLink: "",
					StoreLinkSec: "",
				},
			},
			accessories: {
				common: {
					title: "ACCESSORIES",
					description: "Antenna accessories",
				},
				miniTuner: {
					common: {
						series: "Mini Tuner",
						description:
							"Ultra small tuner for EFHW antennas (End Fed Half Wire)",
					},
					long: {
						description:
							"Ultra small and lightweight tuner for EFHW (End Fed Half Wire) type antenna with SWR indicator. No SWR meter in the transceiver is required for effective antenna tuning. It provides tuning of the half-wave radiator (half-wavelength antenna wire of a given band) to resonance in the 40m/30m/20m/15m bands. You won't damage the transceiver's power output stage with a mismatched antenna - the tuner circuit has a built-in artificial load, used when tuning the radiator (tuning/operation switch). Tuning is indicated by a red LED. A version equipped with a BNC connector, allowing the tuner to be connected directly to the transceiver without the use of a coaxial cable.",

						model: "Mini-Tuner BNC plug",
						weight: "70g",
						power: "10W P.E.P",
						size: "60x40x30",
						feeder: "BNC plug",
						antenna:
							"2x banana (for radiator red, for counterweight black)",
						storeLink: "/distributors#",
					},
					short: {
						description:
							"Ultra small and lightweight tuner for EFHW (End Fed Half Wire) type antenna with SWR indicator. No SWR meter in the transceiver is required for effective antenna tuning. It provides tuning of the half-wave radiator (half-wavelength antenna wire of a given band) to resonance in the 40m/30m/20m/15m bands. You won't damage the transceiver's power output stage with a mismatched antenna - the tuner circuit has a built-in artificial load, used when tuning the radiator (tuning/operation switch). Tuning is indicated by a red LED.",
						model: "Mini-Tuner BNC socket",
						weight: "70g",
						power: "10W P.E.P",
						size: "60x40x30",
						feeder: "BNC socket",
						antenna:
							"2x banana (for radiator red, for counterweight black)",
						storeLink: "/distributors#",
					},
				},
				redChoke: {
					common: {
						series: "Red-Choke",
						description: "Choke Balun",
						descriptionPage:
							"Virtually every type of antenna fed by coaxial cable at the antenna connection point should have a choke balun. A completely different approach from the classic winding of coaxial cable on ferrite cores is used here, the choke-balun consists of two bifilar windings.",
						weight: "...g",
						power: "max 1.5KW",
						size: "170x75x55",
						sockets: "SO239 (UC1, UHF)",
						cable: "PL259 plug (UC1, UHF) + 60cm RG-213U",
						range: "1-30MHz",
						storeLink: "/distributors#",
					},
				},
				redMount: {
					common: {
						series: "Red-Mount",
						description: "Aluminum mount for vertical antennas",
						descriptionPage:
							"The mount is made of anodized aluminum, allows you to mount the antenna with a 3/8 inch thread and directly plug the spike into the ground (lawn). The spike ensures very fast installation of the antenna in the field, and additionally provides good grounding, required for whip antennas. The spike ends in a thread with a wing nut for convenient connection of additional radials. For connecting coaxial cable, the mount has an SO239 (UC1) socket.",
						storeLink: "/distributors#",
					},
				},
				redCon: {
					common: {
						series: "Red-Con connector kit",
						description: "Universal adapter set",
						connectorsTitle:
							"The set includes the following items:",
					},
					long: {
						model: "Red-Con 01",
						description:
							"Universal set of adapters (reductions) between the most popular types of connectors used in radio communications. Essential for connecting different types of antennas and cables to radios and analyzers. Comes with a handy box for storing and conveniently carrying all items.",
						connectors: [
							"1x BNC plug <-> UHF socket SO239 (UC1) adapter",
							"1x N plug <-> UHF socket adapter (SO239, UC1)",
							"1x BNC socket <-> UHF plug adapter (PL259, UC1)",
							"1x UHF plug adapter (PL259, UC1) <-> N socket",
							"1x adapter plug N -> plug PL259",
							"1x Mini-UHF plug adapter -> SO239 socket (UC1, UHF)",
							"1x Mini-UHF plug adapter -> BNC socket",
							"1x adapter plug SMA-M - UHF socket (SO239, UC1)",
							"1x adapter BNC plug <-> SMA-F socket",
							"1x adapter plug SMA-M <-> BNC socket",
							"1x adapter N plug <-> BNC socket",
							"1x adapter N plug <-> SMA-F plug",
							"1x UHF socket connector <-> UHF socket (SO239, UC1)",
							"1x connector socket SMA-F -> SMA-F",
							"1x connector SMA-M plug <-> SMA-M plug",
							"1x connector BNC socket <-> BNC socket",
							"1x connector SO239 socket -> PL259 plug (UC1, UHF) angle",
						],
						storeLink: "/distributors#",
					},
					short: {
						model: "Red-Con 02",
						description:
							"Universal set of adapters (reductions) between the most popular types of connectors used in radio communications. Essential for connecting different types of antennas and cables to radios and analyzers. Comes with a handy box for storing and conveniently carrying all items.",
						connectors: [
							"1mb RG58 C/U coaxial cable terminated with BNC plugs",
							"2x PL259 plug adapter (UC1, UHF) -> BNC socket",
							"2x adapter N plug -> BNC socket",
							"2x adapter plug N -> BNC socket",
							"2x adapter plug N -> BNC socket",
							"2x SMA-F plug adapter -> BNC socket",
							"2x adapter plug SMA-M -> BNC socket",
							"2x adapter plug SMA-M -> BNC socket",
							"2x BNC socket -> BNC socket adapter",
							"1x BNC connector plug -> BNC connector",
							"1x connector plug PL259 (UC1, UHF) -> angle BNC socket",
							"1x connector BNC socket -> angle BNC plug",
						],
						storeLink: "/distributors#",
					},
				},
				redLine: {
					common: {
						series: "Red-Line",
						descriptionPage:
							"Red-Line is a high-end 50 ohm RG 58 type cable for the most demanding users of such cables. The inner conductor is a cable very precisely twisted from wires made of the highest grade oxygen-free copper ( outer diameter 0.9 mm ). To signal the high quality of workmanship, very good parameters and to distinguish the product on the market, the outer sheath of this cable is unusual - transparent with a slight red tint ( of course, the cable can also be used outdoors, the sheath is UV resistant ). The RG 58 RED shield is made of very dense braid ( 98% ), and the wires in the braid strands are as large as 0.16 mm in diameter.",
						description: "High quality cable type RG 58",
						storeLink: "/distributors#",
					},
				},
			},
		},
	},
};
